config/routes.rb
Rails.application.routes.draw do
 root 'welcome#index'
 get 'dashboards/index'
 get 'welcome/index'
 get "/about", :to => "welcome#about"

 devise_for :users 
 
 resources :contacts
 resources :banners
 resources :orders
 get "lineitems/update"
 resources :stores do
 collection do
 	get :item_display
 end
end
 resources :lineitems
 resources :carts do
    member do
      get :edit_lineitem
      get :update_lineitem
    end
  end

 resources :categories
 resources :stickers do
   collection do
     get :listing
     
   end
 end

end

app/models/banner.rb
class Banner < ActiveRecord::Base
	has_many :images, :as => :imagable
	 validates_uniqueness_of :name
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy

 
def add_sticker(sticker_id)
current_item = lineitems.find_by(sticker_id: sticker_id)
if current_item
current_item.quantity +=1
else
current_item = lineitems.build(sticker_id: sticker_id)
end
return current_item 
end

def unit_price
	lineitems.to_a.sum { |item| item.unit_price }
	end

def total_price
lineitems.to_a.sum { |item| item.total_price }
end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :stickers
	has_many :banners
	has_many :images, :as => :imagable
accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }


end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates  :email, :phone, :message, presence: true
 validates_uniqueness_of :name
has_many :users
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("name LIKE ?", "%#{search}%")
end

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :sticker, dependent: :destroy
	belongs_to :banner,dependent: :destroy
		belongs_to :category,dependent: :destroy
	  belongs_to :imagable, :polymorphic => true
  has_attached_file :image, :styles => {:original => "900x900>",:default => "226x287!",:thumb => "140x140>"}
    validates_attachment_content_type :image, :content_type => %w(image/jpeg image/png)
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :sticker
  belongs_to :cart
   has_many :order

   def unit_price
   	sticker.price
   end
   
 def total_price
		sticker.price * quantity
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :sticker
	has_many :cart
	has_many :lineitem
	mount_uploader :attachment, AttachmentUploader
	 

end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
has_many :images, :as => :imagable
validates :description,:category_id, presence: true
validates_uniqueness_of :name
has_many :users

 #validates :status, :presence => true
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank

 def self.search(search)
    if search.present?
     where('name LIKE ? ',"#{search}")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stickers
	has_many :carts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
 before_filter :is_login?
layout :layout?
	def index
		@banners= Banner.all
		
	end

	def new
		@banner= Banner.new
			1.times{@banner.images.build}
		
	end

	def create
		@banner= Banner.new(banner_params)
			1.times{@banner.images.build} if @banner.images.blank?
		if @banner.save
			redirect_to banners_path
		else
			render "new"
		end
	end

	def show
		@banner= Banner.find(params[:id])
	end

	def edit
		@banner= Banner.find(params[:id])
	end

	def update
		@banner= Banner.find(params[:id])
			1.times{@banner.images.build} if @banner.images.blank?
		if @banner.update(banner_params)
			redirect_to banners_path
		else
			render "edit"
		end
	end

	def destroy
		@banner= Banner.find(params[:id])
		@banner.destroy
		redirect_to banners_path
	end

	private

	def banner_params
		params.require(:banner).permit!
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banner_helper.rb
module BannerHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/banners/_edit_for.html.erb
<%= nested_form_for @banner, html: { multipart: true } do |f| %>

  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='field'>
  
<%= f.fields_for :images do |image| %>
  <%= image.file_field :image %>
  <%= image.link_to_remove "Remove image" %>
<% end %>
<p><%= f.link_to_add "Add a image", :images %></p>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/banners/_form.html.erb
<%= nested_form_for @banner, html: { multipart: true } do |f| %>

  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='field'>
  <% if !@banner.new_record? %>
<br><% @banner.images.each do |i| %>
<%= image_tag(i.image.url, :height => 50, :width =>80 ) %>
<% end %>
<% end %>
<%= f.fields_for :images do |image| %>
  <%= image.file_field :image %>
  <%= image.link_to_remove "Remove image" %>
<% end %>
<p><%= f.link_to_add "Add image", :images %></p>
  </div>

  <%= f.label :name %><br/>
   <div class="form-group">
          <%= f.text_field :name, placeholder: "Name", class: "form-control input-lg", label: false, :required =>true %>
        </div>

        <%= f.submit "Create Banner",class: "btn btn-success"%>
    <% end %>

app/views/banners/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
<h1>Edit Banner</h1>

<%= render 'form' %>

<%= link_to 'Show', @banner %> 
<%= link_to 'Back', banners_path %>
</div>

app/views/banners/index.html.erb
<p id="notice"><%= notice %></p>
<div class="text-right">
<%#= button_to "Back" , dashboards_index_path, :method => "get" %>
<h1><%= link_to '+New Banner', new_banner_path %></h1>
</div>
<style>
   div.text-right{
     float: right;
}
  </style>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
        <th>Banner</th>
      <th>Name</th>
  
      <th>Caption part</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>    
       <td><% banner.images.each do |image| %>
<%= link_to  image_tag(image.image.url, :height => 50, :width =>80 ), banner_path(banner.id) %>
<% end %></td>
        <td><%= banner.name %></td>

        <td><%= link_to 'Show', banner %>
       <%= link_to 'Edit', edit_banner_path(banner) %>
       <%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 <style>
   div.text-right{
     float: right;
}
  </style>


<%#= button_to "new banner", new_banner_path, :class => "button", :method => :get  %>

app/views/banners/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
    <h1>New Banner</h1>

<%= render 'form' %>

<%= link_to 'Back', banners_path %>
</div>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @banner.name %>
</p>
<p>
<% @banner.images.each do |i| %>
<%= image_tag(i.image.url, :height => 50, :width =>80 ) %>
<% end %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> 
<%= link_to 'Back', banners_path %>