config/routes.rb
Rails.application.routes.draw do
 root 'welcome#index'
 get 'dashboards/index'
 get 'welcome/index'
 get "/about", :to => "welcome#about"

 devise_for :users 
 
 resources :contacts
 resources :banners
 resources :orders
 get "lineitems/update"
 resources :stores do
 collection do
 	get :item_display
 end
end
 resources :lineitems
 resources :carts do
    member do
      get :edit_lineitem
      get :update_lineitem
    end
  end

 resources :categories
 resources :stickers do
   collection do
     get :listing
     
   end
 end

end

app/models/banner.rb
class Banner < ActiveRecord::Base
	has_many :images, :as => :imagable
	 validates_uniqueness_of :name
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy

 
def add_sticker(sticker_id)
current_item = lineitems.find_by(sticker_id: sticker_id)
if current_item
current_item.quantity +=1
else
current_item = lineitems.build(sticker_id: sticker_id)
end
return current_item 
end

def unit_price
	lineitems.to_a.sum { |item| item.unit_price }
	end

def total_price
lineitems.to_a.sum { |item| item.total_price }
end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :stickers
	has_many :banners
	has_many :images, :as => :imagable
accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }


end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates  :email, :phone, :message, presence: true
 validates_uniqueness_of :name
has_many :users
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("name LIKE ?", "%#{search}%")
end

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :sticker, dependent: :destroy
	belongs_to :banner,dependent: :destroy
		belongs_to :category,dependent: :destroy
	  belongs_to :imagable, :polymorphic => true
  has_attached_file :image, :styles => {:original => "900x900>",:default => "226x287!",:thumb => "140x140>"}
    validates_attachment_content_type :image, :content_type => %w(image/jpeg image/png)
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :sticker
  belongs_to :cart
   has_many :order

   def unit_price
   	sticker.price
   end
   
 def total_price
		sticker.price * quantity
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :sticker
	has_many :cart
	has_many :lineitem
	mount_uploader :attachment, AttachmentUploader
	 

end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
has_many :images, :as => :imagable
validates :description,:category_id, presence: true
validates_uniqueness_of :name
has_many :users

 #validates :status, :presence => true
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank

 def self.search(search)
    if search.present?
     where('name LIKE ? ',"#{search}")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stickers
	has_many :carts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/stickers_controller.rb
class StickersController < ApplicationController
layout :layout?
before_filter :is_login?,only: [:new,:index,:edit,:show]
def index
	if params[:category].blank?
@stickers=Sticker.all.order("created_at ASC")
	
else
@category_id = Category.find_by(:name=>params[:category]).id
@stickers = Sticker.where(category_id: @category_id).order("created_at DESC")
end
end

	def new
@sticker= Sticker.new
	1.times{@sticker.images.build}
	@status = params[:status]
	end

	def create
		@sticker= Sticker.new(sticker_params.merge(user_id:current_user.id))
	@status = @sticker.status
		1.times{@sticker.images.build} if @sticker.images.blank?
		if @sticker.save

			redirect_to stickers_path #:notice => "Successfully created sticker."
			
		else
			render "new"
		end
	end

	def show
		@sticker= Sticker.find(params[:id])
   
	end

	def edit
		@sticker= Sticker.find(params[:id])
	end

	def destroy
		@sticker= Sticker.find(params[:id])
		@sticker.destroy
		redirect_to stickers_path
	end

def update
		@sticker= Sticker.find(params[:id])
		1.times{@sticker.images.build} if @sticker.images.blank?
		if @sticker.update(sticker_params)
			redirect_to stickers_path
		else
			render "edit"
		end
	end

	def listing
     @stickers= Sticker.all
    respond_to do |format|
      format.js
    end
  end

private

def sticker_params
	params.require(:sticker).permit!
end
end

app/helpers/banner_helper.rb
module BannerHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/stickers/_form.html.erb
<%= nested_form_for @sticker, html: { multipart: true } do |f| %>
<%= f.hidden_field :status ,:value => params[:status] %>

  <% if @sticker.errors.any? %>

    <div id="error_explanation">

      <h2><%= pluralize(@sticker.errors.count, "error") %> prohibited this sticker from being saved:</h2>

      <ul>
      <% @sticker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

      </ul>
    </div>
  <% end %>

    <%#= f.label :category_id %>
    <%#= f.collection_select :category_id, Category.all, :id, :name %>
    <div class="form-group">
    <%= f.select(:category_id, Category.all.map {|c| [c.name, c.id]}, :prompt =>"Choose a Category")%>
  </div>
<% if !@sticker.new_record? %>
<br><% @sticker.images.each do |i| %>
<%= image_tag(i.image.url, :height => 50, :width =>80 ) %>
<% end %>
<% end %>
  <div class='field'>
<%= f.fields_for :images do |image| %>
  <td><%= image.file_field :image %></td>
  <p><%= image.link_to_remove "Remove image" %></p>
<% end %>
<p><%= f.link_to_add "Add a image", :images %></p>
</div>

 <%= f.label :name %><br/>
    <div class="form-group">
        <%= f.text_field :name, placeholder: "Name", class: "form-control input-lg", label: false, :uniqueness_of => true, :required =>true %>
    </div>
 
   <%= f.label :price %><br/>
    <div class="form-group">
        <%=  f.text_field :price, placeholder: "Price", class: "form-control input-lg", label: false %>
    </div>
<%= f.label :quantity %><br/>
    <div class="form-group">
        <%=  f.text_field :quantity, placeholder: "Quantity", class: "form-control input-lg", label: false %>
    </div>

  <%= f.label :description %><br/>
    <div class="form-group">
      <%= f.text_area :description, placeholder: "Description", class: "form-control input-lg", label: false, :required =>true %>
    </div>

  <%= f.submit "Create Sticker",class: "btn btn-success"%>
    <% end %>

app/views/stickers/_search.html.erb
 <%=  form_tag stores_path(), :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil,class: "btn btn-success" %> 
<% end %>

app/views/stickers/_slider.html.erb
 <ul class="bxslider1" i>
<% @stickers.each do |i| %>

<% for image in i.images %>

<li><%=link_to  image_tag(image.image.url, :height => 180, :width => 200 ),  store_path(i.id) %>
<%= link_to i.name, store_path(i.id) %><br>
$<%= i.price %><br>
<div class="floating"><%= button_to 'Add to Cart', lineitems_path(sticker_id: i),class: "btn btn-warning btn-sm"  %></div>
<div class="floating"><%= link_to 'More info',store_path(i.id),class: "btn btn-success" %></div></li>
     
<% end %>
<% end %>

</ul>
<script >


$('.bxslider1').bxSlider({
   slideWidth:300,
    minSlides: 2,
    maxSlides: 4,
    startSlide: 2,

    pager: false,
    auto: true,
autoHover: true
});

</script>
<style>
.floating {
	display:inline-block;
                  margin: 4px;
                  }

                 </style>

app/views/stickers/_sticker_all.html.erb
<p id="notice"><%= notice %></p>
<h1><%= link_to "+New Sticker", new_sticker_path %></h1>
<div class="text-right">
<%= button_to "Back" , dashboards_index_path, :method => "get" %>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th> 
      <th>Images</th>
   <th>Caption part</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @stickers.each do |sticker| %>
      <tr>
        <td><%= sticker.name %></td>
        <td><%= sticker.description %></td>
        <td><%= sticker.price %></td>
      <td><% sticker.images.each do |image| %>
<%= link_to  image_tag(image.image.url, :height => 50, :width =>80 ), sticker_path(sticker.id) %>
<% end %></td>

      </tr>
      
    <% end %>
  </tbody>
</table>
 
<br>
<style>
   div.text-right{
     float: right;
}
  </style>

app/views/stickers/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
    <h1>Editing Sticker</h1>

<%= render 'form' %>

<%= link_to 'Show', @sticker %> 
<%= link_to 'Back', stickers_path %>
</div>

app/views/stickers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="text-right">
<h1><%= link_to "+New Sticker", new_sticker_path %></h1>

<%#= button_to "Back" , dashboards_index_path, :method => "get" %>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
     <th>Stickers</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th> 
      <th>Quantity</th>
     
   <th>Caption part</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @stickers.each do |sticker| %>
      <tr>
           <td><% sticker.images.each do |image| %>
<%= link_to  image_tag(image.image.url, :height => 50, :width =>80 ), sticker_path(sticker.id) %>

<% end %></td>
        <td><%=link_to sticker.name, sticker_path(sticker.id) %></td>
        <td><%= sticker.description %></td>
        <td><%= sticker.price %></td>
        <td><%= sticker.quantity %></td>
 
<td><%= link_to 'Show', sticker %>
        <%= link_to 'Edit', edit_sticker_path(sticker) %>
      <%#= button_to 'Add to Cart', lineitems_path(sticker_id: sticker) %>
       <%= link_to 'Destroy', sticker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     
    <% end %>
  </tbody>
</table>
 
<br>
<style>
   div.text-right{
     float: right;
}
  </style>

app/views/stickers/listing.js.erb
$("#sticker_all").html('<%= escape_javascript render :partial => '/stickers/sticker_all' %>');

app/views/stickers/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
    <h1>Add sticker </h1>

<%= render 'form' %>
<%= link_to 'Back', stickers_path %>
 
</div>

app/views/stickers/search.html.erb
<%= form_tag(stickers_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
<%= submit_tag "Search" %>
<% end %>

app/views/stickers/show.html.erb
<% @sticker.images.each do |image| %>

<td><%= image_tag(image.image.url, :height => 140, :width =>140 ) %></td>

<% end %>
<br>
  <strong>Name:</strong>
  <%= @sticker.name %>
<br>
  <strong>Price:$</strong>
  <%= @sticker.price %>
  <%= form_for @sticker, html: { multipart: true } do |f| %>

<%= f.label :quantity %>
<%= f.text_field :quantity %>
  <% end %>
<%= link_to 'Back', stickers_path %>

 <%#= link_to "list of stickers",  listing_stickers_path, :remote => true %>
 