config/routes.rb
Rails.application.routes.draw do
 root 'welcome#index'
 get 'dashboards/index'
 get 'welcome/index'
 get "/about", :to => "welcome#about"

 devise_for :users 
 
 resources :contacts
 resources :banners
 resources :orders
 get "lineitems/update"
 resources :stores do
 collection do
 	get :item_display
 end
end
 resources :lineitems
 resources :carts do
    member do
      get :edit_lineitem
      get :update_lineitem
    end
  end

 resources :categories
 resources :stickers do
   collection do
     get :listing
     
   end
 end

end

app/models/banner.rb
class Banner < ActiveRecord::Base
	has_many :images, :as => :imagable
	 validates_uniqueness_of :name
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy

 
def add_sticker(sticker_id)
current_item = lineitems.find_by(sticker_id: sticker_id)
if current_item
current_item.quantity +=1
else
current_item = lineitems.build(sticker_id: sticker_id)
end
return current_item 
end

def unit_price
	lineitems.to_a.sum { |item| item.unit_price }
	end

def total_price
lineitems.to_a.sum { |item| item.total_price }
end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :stickers
	has_many :banners
	has_many :images, :as => :imagable
accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }


end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates  :email, :phone, :message, presence: true
 validates_uniqueness_of :name
has_many :users
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("name LIKE ?", "%#{search}%")
end

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :sticker, dependent: :destroy
	belongs_to :banner,dependent: :destroy
		belongs_to :category,dependent: :destroy
	  belongs_to :imagable, :polymorphic => true
  has_attached_file :image, :styles => {:original => "900x900>",:default => "226x287!",:thumb => "140x140>"}
    validates_attachment_content_type :image, :content_type => %w(image/jpeg image/png)
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :sticker
  belongs_to :cart
   has_many :order

   def unit_price
   	sticker.price
   end
   
 def total_price
		sticker.price * quantity
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :sticker
	has_many :cart
	has_many :lineitem
	mount_uploader :attachment, AttachmentUploader
	 

end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
has_many :images, :as => :imagable
validates :description,:category_id, presence: true
validates_uniqueness_of :name
has_many :users

 #validates :status, :presence => true
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank

 def self.search(search)
    if search.present?
     where('name LIKE ? ',"#{search}")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stickers
	has_many :carts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 before_action :set_cart, only: [:show, :edit, :update, :destroy]
  
  def index
    @cart = current_cart   
  end
  
  def show

  end
  
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Lineitem.find(params[:id])
    @item.destroy
    redirect_to carts_path(current_cart)
  end

  private
   
    def set_cart
      @cart = current_cart
    end

    def cart_params
      params.require[:cart].permit!
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to sticker_url, notice: 'Invalid cart'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banner_helper.rb
module BannerHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart.html.erb
<h2>Your Cart</h2>
<table>
  
<tr class="total_line">
<td colspan="2">Total</td>
<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
</tr>
</table>
 <%= button_to "Checkout", new_sticker_path, method: :get %>
<%= button_to 'Empty cart', cart, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/carts/_edit_lineitem.html.erb
<%= form_for @lineitem, :url => update_lineitem_cart_path(@lineitem), :method => 'PUT', :html => {:id => "search-query"}, :remote => true do |f| %>
  <%= f.text_field :quantity, :style => 'width: 10px;' %>
  <%= f.submit "Add" %>
<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :sticker_id %><br>
    <%= f.text_field :sticker_id %>
  </div>
  
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>

  <div class="field">
  <%= text_field_tag 'quantity' %>
    </div>
    
  <div class="field">
  <%= f.label :unit_price %><br>
  <%= f.text_field :unit_price %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/carts/_index.html.erb
<table class="table table-bordered"> 
    <td class="field-label col-xs-3 active">
  <thead>
  <hr/>
    <tr>
     <th></th>
     <th>Item</th>
     <th>Quantity</th>
     <th class="price">Price</th>
     <th class="price">Total</th>
     <th></th>
  
 </thead>
 <% for lineitem in @cart.lineitems %>
 <tbody>
   <tr class="<%= cycle :odd, :even %>">
    <td>
      <% lineitem.sticker.images.where("image_show = #{true}").each do |img| %>
      <li>
        <% if img.try(:photo).present? && img.image_show? %>
        <%=image_tag img.photo.url(:original),:style=>"width:40%;height:40%;" %>
        <% end %>
      </li>
      <% end %>
    </td>

    <td><%=h lineitem.sticker.name %></td>
    <td class="quantity">
      <%= select_tag :quantity, options_for_select(@quantities, :selected => lineitem.quantity), :onchange => "quantity_select(this.value, #{current_cart.id}, #{line_item.id})" %>
    </td>

    <td class="price"><%= number_to_currency(lineitem.unit_price) %></td>
    <td class="price"><%= number_to_currency(lineitem.full_price) %></td>

    <td><%= link_to "close", cart_path(lineitem), :method => :delete, :confirm => "	Are You Sure",:class => "fa fa-close" %></td>
  </tr>
 
<% end %>
</tbody>
<tfoot>
 </td>
  <tr>
    <td colspan="6" >
      Grand Total: <h4><%= number_to_currency @cart.total_price %></h4>
    </td>
  </tr>
</tfoot>
</table>
<p>

<% if @cart.total_price  %>
  <%= link_to "CHECKOUT >", new_sticker_path ,class: "pull-right btn btn-default "%>
  <% end %> 





</p>
<script type="text/javascript">
  function quantity_select(quantity, cart, lineitem)
  {
    $.ajax({
      url: "/carts/" + lineitem,
      dataType: "Script",
      method: "PUT",
      data: {
        quantity: quantity,
        cart: cart
      }
    });
    // $("#btn-save_"+ line_item).show();
  }
  
</script>

   

app/views/carts/_show.html.erb
<h1><%#= button_to "Continue Shoping" , stores_path, :method => "get",class: "btn btn-info btn-lg" %></h1>

 <h3>SHOPPING CART</h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
  
        <th>Sticker</th>
      <th>Sticker Name</th>
      <th>Price</th> 
      <th>Quantity</th>
      <th>SubTotal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @cart.lineitems.each do |item| %>
<tr>

  <td><%=  image_tag(item.sticker.images.first.image.url, :height => 90, :width =>80) %></td>
<td><%= item.sticker.name %></td>

 <td class="item_price"><%= number_to_currency(item.unit_price) %></td>
      <%= form_for item, :url => lineitem_path(item),  remote:true do |f| %>
      <td class="a-center movewishlist"><%= f.number_field :quantity, maxlength: "12", id: "cart-qty", class: "input-text qty", title: "Qty", size: '5', min: '1', max: '99', data: { item_id: item.id } %>
       <%#= f.hidden_field :sticker_id, value: item.id %>
      <%= f.submit '+add' %>
     
        <%#= item.quantity %>              
  <% end %> </td> 

<td colspan="2"><%= number_to_currency(item.total_price) %>
  <td><%= link_to ('<span class="glyphicon glyphicon-trash"> </span>').html_safe, cart_path(item) , method: :delete, data: { confirm: 'Are you sure?'} %></td>
   
</tr> 

<% end %>

</tbody>
 <tr>

<div class="col-md-5 col-md-offset-4">
<div class="floating"><td><td><td><td><h4>Estimated Total<td> <%= number_to_currency(@cart.total_price) %></td></td></td></td></td></h4></div></td></td></td></td></td>
  </tr>
</table>
   <div class="text-right">
 <td>
 <div class="floating"><%= button_to "Continue Shopping" ,root_path, :method => "get",class: "btn btn-success" %></div>

<div class="floating"><%= button_to "Process To Checkout",new_order_path, :method => "get" ,class: "btn btn-warning" %></div></li></td></div>
 <table class="table table-bordered table-striped">
<tbody>
 

</div>
</td></div></div></tr></tbody></table>
</tr>  
 </div>
 </div>
 
 


 <style>
   div.text-right{
     float: right;
   }
  </style><br>

  <style>
.floating {
  display:inline-block;
                  margin: 0px;
                  }
</style>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> 
<%= link_to 'Back', carts_path %>

app/views/carts/edit_lineitem.js.erb
$('#qua').hide();
$('#lineitem_quantiy_<%= @lineitem.id %>').html('<%= escape_javascript render :partial => 'carts/edit_lineitem' %>');

app/views/carts/index.html.erb
<%= render :partial => 'show' %>

app/views/carts/new.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div class="text-right">

<h1> <div class="floating"><%= button_to "Continue Shoping" ,stores_path, :method => "get",class: "btn btn-success" %></div></h1>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
        <th>Sticker</th>
      <th>Sticker Name</th>
      <th>Price</th> 
      <th>Quantity</th>
      <th>SubTotal</th>
      <th>Estimated Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <%= image_tag("images14.jpg", alt: "Fancy", size: "2150*2150")%> </table>
<style>
   div.text-right{
     float: right;
}
  </style>
 

app/views/carts/show.html.erb
<div id="total_items">
<%= render :partial => '/carts/show' %>
</div>

app/views/carts/update.js.erb
$('#cart').html('<%= escape_javascript render :partial => 'show'%>');