config/routes.rb
Rails.application.routes.draw do
 root 'welcome#index'
 get 'dashboards/index'
 get 'welcome/index'
 get "/about", :to => "welcome#about"

 devise_for :users 
 
 resources :contacts
 resources :banners
 resources :orders
 get "lineitems/update"
 resources :stores do
 collection do
 	get :item_display
 end
end
 resources :lineitems
 resources :carts do
    member do
      get :edit_lineitem
      get :update_lineitem
    end
  end

 resources :categories
 resources :stickers do
   collection do
     get :listing
     
   end
 end

end

app/models/banner.rb
class Banner < ActiveRecord::Base
	has_many :images, :as => :imagable
	 validates_uniqueness_of :name
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy

 
def add_sticker(sticker_id)
current_item = lineitems.find_by(sticker_id: sticker_id)
if current_item
current_item.quantity +=1
else
current_item = lineitems.build(sticker_id: sticker_id)
end
return current_item 
end

def unit_price
	lineitems.to_a.sum { |item| item.unit_price }
	end

def total_price
lineitems.to_a.sum { |item| item.total_price }
end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :stickers
	has_many :banners
	has_many :images, :as => :imagable
accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }


end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates  :email, :phone, :message, presence: true
 validates_uniqueness_of :name
has_many :users
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("name LIKE ?", "%#{search}%")
end

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :sticker, dependent: :destroy
	belongs_to :banner,dependent: :destroy
		belongs_to :category,dependent: :destroy
	  belongs_to :imagable, :polymorphic => true
  has_attached_file :image, :styles => {:original => "900x900>",:default => "226x287!",:thumb => "140x140>"}
    validates_attachment_content_type :image, :content_type => %w(image/jpeg image/png)
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :sticker
  belongs_to :cart
   has_many :order

   def unit_price
   	sticker.price
   end
   
 def total_price
		sticker.price * quantity
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :sticker
	has_many :cart
	has_many :lineitem
	mount_uploader :attachment, AttachmentUploader
	 

end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
has_many :images, :as => :imagable
validates :description,:category_id, presence: true
validates_uniqueness_of :name
has_many :users

 #validates :status, :presence => true
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank

 def self.search(search)
    if search.present?
     where('name LIKE ? ',"#{search}")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stickers
	has_many :carts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/banner_helper.rb
module BannerHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class ="footer navbar-fixed bottom">
<div class="content">
    <div class="commonrow">
      <div class="image" >
<%= link_to image_tag("onlinesticker.png", alt: "File Name Fancy", size: "2150*2150"), root_path %>
    </div>
    <div class="commonrow">
      <div class="aboutusBox">
      <div class="text">
     
                <h4><span><span><%= link_to 'About_us', about_path,class: "btn btn-primary"  %></span></span></h4></div>
<div class="text">
        <p>Onlinesticker is a e-commerce platform to "Discover Unique Hand crafted Products" including Handmade, Vintage, Ethnic, Organic,IT and Natural products. 
<br><br>
Onlinesticker is a beautiful assortment of diversity reflected in our Clothing, Food, Lifestyle, Language, Music, Books and other online digital art, etc. This diversity is so rich and diverse that an attempt to capture it on a single platform was never made. Onlinesticker is that sincere attempt by bunch of young insane guys and girls who think this is possible now with the Internet. These are the modern internet entrepreneurs.
<br><br>
Experience the exquisite craftsmanship from the new age of entrepreneurs. We sincerly hope for all our customers to have an amazing experience with our super fast deliveries and policies which are very much customer oriented. 
  </p>
      </div>
    </div>
    <div class="commonrow">
      <ul class="list-media-footer">
        <%#= render 'layouts/social' %>
      </ul>
    </div>
    <div class="menu-footer">
     <div class="text">
          <h4>Information</h4>

           <td><%= link_to "About Us", about_path %></td><br>
           <td><%= link_to "Delivery Information", root_path %></td><br>
           <td><%= link_to "Privacy Policy", root_path %></td><br>
           <td><%= link_to "Terms & Conditions", root_path %></td><br>
           <td><%= link_to "Legal Disclaimer", root_path %></td><br>
     
      </div>
    </div>
   <div class="text-center">
      Copyright © 2016 Onlinesticker. All rights reserved.
    </div>
    <div class="clearFix"></div>
  </div>
</footer>
</footer>
<style>
#footer {
    clear: both;
    height: 450px;
    color:#ccc;
    font-size:12px;
    position:relative;
    z-index: 10;
    margin-top: -3em;
    margin-right: -5.3em;
    margin-left: -5.2em;
    background-color:#31353a;
}
</style>
<style>
   div.text-center{
     float: center;

}
div.text{
     margin-left: 75px;
     margin-right: 75px;
     margin-bottom: 10px;
     

}

div.image{
  padding-top: 20px;
     margin-left: 70px;
}

  </style>

app/views/layouts/_header.html.erb
<%= link_to ('Home <span class="glyphicon glyphicon-home"> </span>').html_safe,   root_path %>
<%= link_to 'About_us', about_path %> 
<%= link_to ('Contact <span class="glyphicon glyphicon-phone-alt"> </span>').html_safe, new_contact_path %>
<br>
<%= link_to image_tag("onlinesticker.png", alt: "File Name Fancy", size: "2150*2150"), root_path %> 

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineSticker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

</head>
<body>

  <nav id ="nav">

 </div> 

<div id= "page_nav" >
<p><%= render 'layouts/header' %></p>
     </div>
             

<div id= "sign_in" >
<% if current_user.present? %>


<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
 <% elsif current_user and current_user.role == 'admin' %>
 
<% else %>
<%= form_tag stores_path, :id => 'search_form', :method => :get do %>
 <%= select_tag :category, options_for_select([["stickers",""]]+Category.all.map{|a| a.name}), :style => "border: 1px solid white;" %>
<% end %>

<%= link_to ("Carts (#{
 current_cart.lineitems.count })<span class='glyphicon glyphicon-shopping-cart'> </span>").html_safe,carts_path(current_cart) %>

<%= link_to ('Sign in <span class="glyphicon glyphicon-user"> </span>').html_safe, new_user_session_path(current_user)  %>

<%= link_to ('Sign up <span class="glyphicon glyphicon-folder-open"> </span>').html_safe,  new_user_registration_path(:role => "buyer") %>

<% end %>
</div>


  
</nav>

<div id= "main_wrap" >



<p><%= render 'layouts/navbar' %></p>

<%= yield %>
  <div id="sticker_all"></div>
  <div id="item_all"></div>
</body>
</html>



   

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineSticker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav id ="nav">
 </div> 

<div id= "page_nav" >
     </div>
                     
<div id= "sign_in" >
<%=link_to current_user.role,  "#",class:"glyphicon glyphicon-user"%>
 <% if current_user and current_user.role == 'admin' %>
 
<%= link_to ('<span class="glyphicon glyphicon-off"></span>').html_safe, destroy_user_session_path, :method => :delete %>


<% else %>
<%#= link_to 'Sign in', new_user_session_path(current_user)  %>

<%#= button_to "Sign_up" ,  new_user_registration_path(:role => "bayer"), :method => "get" %>

<% end %>

</div>
</nav>

<div id= "main_wrap" >
 <div class="onlinesticker-container onlinesticker-border">


<h4><p class="notice"><%= notice %></p></h4>
<p><%#= render 'stickers/search' %></p>

<div class="row">
  <div class="col-md-2"</div>
  <li>
    <h5><%= link_to 'DashboardManagement',dashboards_index_path,class:"glyphicon glyphicon-blackboard" %></h5>
<h5><%= link_to "Stickermanagement" ,stickers_path,class:"glyphicon glyphicon-grain" %></h5>       

<h5><%= link_to "annermanagement" ,banners_path,class:"glyphicon glyphicon-bitcoin" %></h5> 

<h5><%= link_to "ContactRequest" ,contacts_path,class:"
glyphicon glyphicon-earphone" %></h5>

<h5><%= link_to "Ordermanagement" ,orders_path,class:"glyphicon glyphicon-folder-open" %></h5>

</div>
</li>
</li>
  <div class="row">

  <div class="col-md-9"</div>

<%= yield %>

</div>
</div>

 <div id="sticker_all"></div>

<div id= "footer" >


 
</footer>

</body>
</html>
</div>

<style>
body {
    margin: 0px;
       width:100%;
           height: 0%;
}
li {
    list-style-type: none;
    margin: -30px;
    padding:5px ;
    width: -5%;
    background-color:lightgray;
    position: fixed;
    height: 100%;
    overflow: auto;
}

li a {
    display: block;
    color: #000;
    padding: 8px 0 8px 16px;
    text-decoration: none;
}

h5 {
    background-color: #4CAF50;
     padding: 10px 0 8px 16px;
    color: white;
}

li :hover:not(.active) {
    background-color: #555;
    color: white;
}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineSticker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

</head>
<body>

  <nav id ="nav">

 </div> 

<div id= "page_nav" >
<p><%= render 'layouts/header' %></p>
     </div>
             

<div id= "sign_in" >

<% if current_user.present? %>

 <%=link_to current_user.name,"#",class:"glyphicon glyphicon-user" %>
<%= link_to ('<span class="glyphicon glyphicon-off"></span>').html_safe, destroy_user_session_path, :method => :delete %>
<%= form_tag stores_path, :id => 'dropdown', :method => :get do %>
 <%= select_tag :category, options_for_select([["Stickers",""]]+Category.all.map{|a| a.name}), :style => "border: 1px solid green;" ,class: "btn btn-primary" %>
<% end %>

<%= link_to ("Carts (#{current_cart.lineitems.count})<span class='glyphicon glyphicon-shopping-cart'> </span>").html_safe,cart_path(current_cart) %>

 <% elsif current_user and current_user.role == 'admin' %>

<% else %>

<%= form_tag stores_path, :id => 'dropdown', :method => :get do %>
 <%= select_tag :category, options_for_select([["Stickers",""]]+Category.all.map{|a| a.name}), :style => "border: 1px solid green;" ,class: "btn btn-primary" %>

<% end %>


<%= link_to ("Carts (#{
current_cart.lineitems.count})<span class='glyphicon glyphicon-shopping-cart'> </span>").html_safe,cart_path(current_cart)%><%#= link_to number_to_currency(@cart.total_price),"#" %>

<%= link_to ('<span class="glyphicon glyphicon-user"> </span> Sign in / Sign up ' ).html_safe, new_user_session_path(current_user)  %>
<%#= link_to ('<span class="glyphicon glyphicon-folder-open"> </span> ').html_safe,  new_user_registration_path(:role => "buyer") %>

<% end %>

</div>

<div class="center">
   <%= form_tag stores_path, :method => 'get',:id => "stickers_search" do %>    
   <div class="inner-addon float: left;">
<i class="glyphicon glyphicon-search"></i>
    <%= text_field_tag :search, params[:search],placeholder: "Search Items", class:"btn btn-default" %>
    <%= submit_tag "Search", :name => nil,class:"btn btn-warning" %> 
<% end %>
  

</div>

</nav>

<div id= "main_wrap" >



<p><%#= render 'layouts/navbar' %></p>

<%= yield %>



  <div id="sticker_all"></div>
  <div id="item_all"></div>
</body>
</html>
<style>
#dropdown
  {
    left: -130px;
    margin-top: -45px;
    position: relative;
    top: 45px;
    width: 102px;
  }

.center
  {
    display:inline-block;
    padding: 2px 55px;
    margin: 65px;
  }

</style>

<script>
  $('#category').change(function()
 {
     $('#dropdown').submit();
 });
</script>